# Generated by Django 4.2.29 on 2026-04-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StorefrontBranding",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        blank=True,
                        help_text="Shown in the header and footer. Leave blank to use Oscar settings.",
                        max_length=255,
                        verbose_name="Store name",
                    ),
                ),
                (
                    "shop_tagline",
                    models.CharField(
                        blank=True,
                        help_text="Used in the browser title. Leave blank to use Oscar settings.",
                        max_length=255,
                        verbose_name="Tagline",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. If empty, the default static logo is used.",
                        upload_to="storefront/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "announcement_badge_label",
                    models.CharField(
                        default="Live",
                        help_text="Short label in the ticker badge (e.g. Live, News).",
                        max_length=64,
                        verbose_name="Announcement badge label",
                    ),
                ),
                (
                    "announcement_line_1",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Announcement line 1"
                    ),
                ),
                (
                    "announcement_icon_1",
                    models.CharField(
                        default="fas fa-truck",
                        help_text="Font Awesome classes, e.g. fas fa-truck",
                        max_length=128,
                        verbose_name="Line 1 icon CSS classes",
                    ),
                ),
                (
                    "announcement_line_2",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Announcement line 2"
                    ),
                ),
                (
                    "announcement_icon_2",
                    models.CharField(
                        default="fas fa-star",
                        max_length=128,
                        verbose_name="Line 2 icon CSS classes",
                    ),
                ),
                (
                    "announcement_line_3",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Announcement line 3"
                    ),
                ),
                (
                    "announcement_icon_3",
                    models.CharField(
                        default="fas fa-th-large",
                        max_length=128,
                        verbose_name="Line 3 icon CSS classes",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Storefront branding",
                "verbose_name_plural": "Storefront branding",
            },
        ),
    ]
