# Generated by Django 5.2.12 on 2026-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='gateway_pay_gateway_326cef_idx',
            old_name='gateway_pay_gateway_63ad31_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='gateway_pay_order_n_32ef4d_idx',
            old_name='gateway_pay_order_n_0fc320_idx',
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='manual_account_number',
            field=models.CharField(blank=True, help_text='Snapshot: paybill account number.', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='manual_confirmation_code',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa confirmation / transaction code entered by customer.', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='manual_paybill',
            field=models.CharField(blank=True, help_text='Snapshot: business paybill shown to customer.', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway',
            field=models.CharField(choices=[('mpesa', 'Lipa na M-Pesa'), ('paypal', 'PayPal'), ('manual', 'M-Pesa Paybill (manual)')], db_index=True, max_length=20),
        ),
    ]
